### ISSUE TITLE
Razer DeathStalker

### ISSUE THREAD

**Issue by redaxmedia** [pez2001/razer_blackwidow_chroma_driver#23]
Hello,

can you give a roadmap about written driver for the Razer DeathStalker?
Is there a way to help coding porting the driver?

**Comment by StephanieSunshine** [comment]
I doubt this tool will ever help you with your DeathStalker.  This is specifically for dealing with the chroma features of the BlackWidow.

**Comment by redaxmedia** [comment]
Search for "Stretch Goal 2" inside the README.md

**Comment by terrycain** [comment]
Its extremely hard to write a driver to a device you don't own, I assume that's why no progress has been made on it.

If you want to help you could try and reverse engineer the usb traffic. Not an easy task. At some point when I can be bothered I might write a page on how I did it for the Chroma and Ultimate 2013 keyboards (I assume the others that have done the same did it in the same or similar ways).

**Comment by duanejeffers** [comment]
@terrycain I just got the Deathstalker Chroma keyboard, and I'm willing to help. I don't know how to reverse engineer USB traffic, but I'm willing to learn (hell, I'll probably google it when I'm done with this message). Let me know what you need from me, and I'll pass it on. :-)

**Comment by terrycain** [comment]
@duanejeffers looking at the layout, in theory Razer should have been lazy and just copied the chroma firmware onto it so it *should* just work but I would rather be sure as between the 3 keyboards I've done there has been some subtle differences. I was debating on creating a wiki page on how to do it. I'll create a page on doing just that later. ;)

You'll need wireshark, sudo, virtualbox with a windows VM on it running that synapse program.

**Comment by redaxmedia** [comment]
I would be happy to help out, just give me a wiki...

**Comment by terrycain** [comment]
If I haven't made the Wiki page by Sunday, prod me again as I would have forgotten but I aim to do it this evening.
